name: Support Pane Bug Report
description: |
  File a bug report from uBlock Origin (uBO)'s "Support" pane, which auto-fills essential information.
body:
  - type: markdown
    attributes:
      value: |
        Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from the [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/) and a fully substantiated analysis supporting the claim.
        New filter list requests are not permitted and will be declined and closed.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        To rule out invalid issues, confirm and check each one of the checkboxes.
        If [disabling uBO](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) makes the issue go away, then it is a filter issue.
        See what [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) reports when you reproduce the issue, this will help you determine whether this is a filter issue.
        If the issue is still present after disabling uBlock Origin (uBO) in the browser, it is unrelated to uBO.
      options:
        - label: I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true
        - label: The issue is not present after disabling uBO in the browser.
          required: true
        - label: I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.
          required: true

  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: uBO is the only extension.
          required: true
        - label: using a new, unmodified browser profile.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Description of the bug or feature.
    validations:
      required: true

  - type: input
    attributes:
      label: A specific URL where the issue occurs.
      description: An exact URL is MANDATORY for an issue affecting a web page, even if it happens "everywhere."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Provide as much detail as possible. We must be able to reproduce to investigate.
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Actual behavior
      description: What happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Configuration
      description: |
        If this section gets automatically filled by uBO, leave it alone.
    validations:
      required: true
