name: Security Vulnerability Disclosure
description: Disclose a significant security vulnerability through a private email.
body:
  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I confirm that I have identified a significant security vulnerability and will report it through a private email.
          required: true

  - type: markdown
    attributes:
      value: |
        All issues are usually public except in cases where disclosure of a significant security vulnerability could lead to malicious actors crafting exploits in the wild.

        **Email:** ubo-security [at-sign] raymondhill.net

        You do not need to click the _"Submit new issue"_ button. This template is just to let you know the actual email address for where to send the report.
